-- 사례 2. 기능 추가에 따른 테이블 구조 변경 및 재구축 (가상, 일반화된 테이블명)
-- 신규 컬럼(MINOR_CD) 추가와 기존 컬럼(ADDR) 길이 변경을 가정한 절차

-- 1. 백업 테이블 생성 및 건수 확인
CREATE TABLE STUDENT_INFO_BAK_20230301 AS
SELECT * FROM STUDENT_INFO;

SELECT COUNT(*) FROM STUDENT_INFO;
SELECT COUNT(*) FROM STUDENT_INFO_BAK_20230301;

-- 2. 변경된 구조로 테이블 재생성
DROP TABLE STUDENT_INFO;

CREATE TABLE STUDENT_INFO (
    STD_NO    VARCHAR2(10)  NOT NULL,
    STD_NM    VARCHAR2(50)  NOT NULL,
    DEPT_CD   VARCHAR2(10),
    ADDR      VARCHAR2(100),            -- 50 > 100 변경
    MINOR_CD  VARCHAR2(10),             -- 신규 컬럼
    REG_DT    DATE DEFAULT SYSDATE,
    CONSTRAINT PK_STUDENT_INFO PRIMARY KEY (STD_NO)
);

-- 3. 데이터 이관
INSERT INTO STUDENT_INFO (STD_NO, STD_NM, DEPT_CD, ADDR, MINOR_CD, REG_DT)
SELECT STD_NO, STD_NM, DEPT_CD, ADDR, NULL, REG_DT
  FROM STUDENT_INFO_BAK_20230301;
COMMIT;

-- 4. 인덱스 재구성 (변동 사항 반영)
CREATE INDEX IX_STUDENT_INFO_01 ON STUDENT_INFO (DEPT_CD, MINOR_CD);

-- 5. 검증: 건수 비교 + 데이터 차이 확인 (0건이면 정상)
SELECT COUNT(*) FROM STUDENT_INFO;

SELECT STD_NO, STD_NM, DEPT_CD, ADDR FROM STUDENT_INFO_BAK_20230301
MINUS
SELECT STD_NO, STD_NM, DEPT_CD, ADDR FROM STUDENT_INFO;
